use_frameworks!

platform :ios, '12.0'

target 'DingYue_iOS_SDK_Example' do
  pod 'DingYue_iOS_SDK', :path => '../'

  target 'DingYue_iOS_SDK_Tests' do
    inherit! :search_paths

    
  end
end
post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                puts "Updated deployment target for #{target.name} to 12.0"
            end
        end
    end
end
