//
// AppleSearchAdsAttributionReportObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** attribution data */
public struct AppleSearchAdsAttributionReportObject: Codable, JSONEncodable, Hashable {

    public var attribution: AppleSearchAdsAttributionReportObjectAttribution

    public init(attribution: AppleSearchAdsAttributionReportObjectAttribution) {
        self.attribution = attribution
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attribution
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attribution, forKey: .attribution)
    }
}

