//
// AppleSearchAdsAttributionReportObjectAttribution.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** attribution data which client get through Apple AdServices API */
public struct AppleSearchAdsAttributionReportObjectAttribution: Codable, JSONEncodable, Hashable {

    public var version31: AppleSearchAdsAttribution
    public var rawData: DYMParamsWrapper

    public init(version31: AppleSearchAdsAttribution,rawData: DYMParamsWrapper) {
        self.version31 = version31
        self.rawData = rawData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case version31 = "Version3.1"
        case rawData = "rawData"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(version31, forKey: .version31)
        try container.encode(rawData.data, forKey: .rawData)
    }
}

