//
// Attribution.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** attribution metadata object */
public struct Attribution: Codable, JSONEncodable, Hashable {

    public var adjustId: String?
    public var appsFlyerId: String?
    public var amplitudeId: String?

    public init(adjustId: String? = nil, appsFlyerId: String? = nil, amplitudeId: String? = nil) {
        if adjustId != nil && adjustId != "" {
            self.adjustId = adjustId
        }
        if appsFlyerId != nil && appsFlyerId != "" {
            self.appsFlyerId = appsFlyerId
        }
        if amplitudeId != nil && amplitudeId != "" {
            self.amplitudeId = amplitudeId
        }
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case adjustId 
        case appsFlyerId
        case amplitudeId
    }

    // Encodable protocol methods
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(adjustId, forKey: .adjustId)
        try container.encodeIfPresent(appsFlyerId, forKey: .appsFlyerId)
        try container.encodeIfPresent(amplitudeId, forKey: .amplitudeId)
    }
}

