//
// ConversionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ConversionRequest: Codable, JSONEncodable, Hashable {

    public enum CoarseValue: String, Codable, CaseIterable {
        case low = "LOW"
        case medium = "MEDIUM"
        case high = "HIGH"
    }
    public var conversionValue: Int
    public var coarseValue: CoarseValue?

    public init(conversionValue: Int, coarseValue: CoarseValue? = nil) {
        self.conversionValue = conversionValue
        self.coarseValue = coarseValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case conversionValue
        case coarseValue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(conversionValue, forKey: .conversionValue)
        try container.encodeIfPresent(coarseValue, forKey: .coarseValue)
    }
}

