//
// EditStringUnit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EditStringUnit: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case string = "string"
        case json = "json"
        case array = "array"
    }
    public var key: String
    public var value: String
    public var type: ModelType?

    public init(key: String, value: String, type: ModelType? = nil) {
        self.key = key
        self.value = value
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case value
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(key, forKey: .key)
        try container.encode(value, forKey: .value)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

