//
// EditOneOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum EditOneOf: Codable, JSONEncodable {
    case typeEditArrayStringUnit(EditArrayStringUnit)
    case typeEditBooleanUnit(EditBooleanUnit)
    case typeEditStringUnit(EditStringUnit)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeEditArrayStringUnit(let value):
            try container.encode(value)
        case .typeEditBooleanUnit(let value):
            try container.encode(value)
        case .typeEditStringUnit(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(EditArrayStringUnit.self) {
            self = .typeEditArrayStringUnit(value)
        } else if let value = try? container.decode(EditBooleanUnit.self) {
            self = .typeEditBooleanUnit(value)
        } else if let value = try? container.decode(EditStringUnit.self) {
            self = .typeEditStringUnit(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of EditOneOf"))
        }
    }
}

