//
// EventReportObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** event list object */
public struct EventReportObject: Codable, JSONEncodable, Hashable {

    /** event list */
    public var events: [Event]

    public init(events: [Event]) {
        self.events = events
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case events
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(events, forKey: .events)
    }
}

