//
// Event.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** event list object */
public struct Event: Codable, JSONEncodable, Hashable {

    /** the name of the event */
    public var name: String
    /** the event extra information if needed */
    public var extra: String?
    public var user: String?

    public init(name: String, extra: String? = nil, user: String? = nil) {
        self.name = name
        self.extra = extra
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case extra
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(extra, forKey: .extra)
        try container.encodeIfPresent(user, forKey: .user)
    }
}

