//
// FirstReceiptVerifyMobileResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FirstReceiptVerifyMobileResponse:Codable, JSONEncodable, Hashable{

    public enum Status: String, Codable, CaseIterable {
        case ok = "ok"
        case fail = "fail"
    }
    public var status: Status = .ok
    public var errmsg: String?
    public var receipt: SubscribedObject?

    public init(status: Status = .ok, errmsg: String? = nil, receipt: SubscribedObject? = nil) {
        self.status = status
        self.errmsg = errmsg
        self.receipt = receipt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case errmsg
        case receipt
    }

    // Encodable protocol methods
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(errmsg, forKey: .errmsg)
        try container.encodeIfPresent(receipt, forKey: .receipt)
    }
}

