//
// Paywall.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** an object describing the purchase page configuration */
public struct Paywall: Codable, JSONEncodable, Hashable {

    /** name */
    public var name: String
    /** paywall version number */
    public var version: Double
    public var subscriptions: [PaywallSubscriptions]
    public var downloadUrl: String

    public init(name: String, version: Double, subscriptions: [PaywallSubscriptions], downloadUrl: String) {
        self.name = name
        self.version = version
        self.subscriptions = subscriptions
        self.downloadUrl = downloadUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case version
        case subscriptions
        case downloadUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(version, forKey: .version)
        try container.encode(subscriptions, forKey: .subscriptions)
        try container.encode(downloadUrl, forKey: .downloadUrl)
    }
}

