//
// ReceiptVerifyPostObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** receipt object */
public struct ReceiptVerifyPostObject: Codable, JSONEncodable, Hashable {

    /** base64 encoded string that represents receipt to be verified. Apple only */
    public var appleReceipt: String?
    /** the token provided to the user's device when the subscription was purchased. Android only */
    public var androidToken: String?

    public init(appleReceipt: String? = nil, androidToken: String? = nil) {
        self.appleReceipt = appleReceipt
        self.androidToken = androidToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case appleReceipt
        case androidToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(appleReceipt, forKey: .appleReceipt)
        try container.encodeIfPresent(androidToken, forKey: .androidToken)
    }
}

