//
// SimpleStatusResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@objcMembers public class SimpleStatusResult: NSObject, Codable, JSONEncodable {

    public enum Status: String, Codable, CaseIterable {
        case ok = "ok"
        case fail = "fail"
    }
    /** the status of the operation */
    public var status: Status
    /** indicated why this operation fails */
    public var errmsg: String?
    public var stacktrace: String?

    public init(status: Status, errmsg: String? = nil, stacktrace: String? = nil) {
        self.status = status
        self.errmsg = errmsg
        self.stacktrace = stacktrace
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case errmsg
        case stacktrace
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(errmsg, forKey: .errmsg)
        try container.encodeIfPresent(stacktrace, forKey: .stacktrace)
    }
}

