//
// SubscriptionPriceTier.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SubscriptionPriceTier: Codable, JSONEncodable, Hashable {

    public var currencyCode: String?
    public var countryCode: String?
    public var price: String?

    public init(currencyCode: String? = nil, countryCode: String? = nil, price: String? = nil) {
        self.currencyCode = currencyCode
        self.countryCode = countryCode
        self.price = price
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currencyCode
        case countryCode
        case price
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(currencyCode, forKey: .currencyCode)
        try container.encodeIfPresent(countryCode, forKey: .countryCode)
        try container.encodeIfPresent(price, forKey: .price)
    }
}

