//
// SwitchItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@objcMembers public class SwitchItem:NSObject, Codable, JSONEncodable {

    public var variableName: String
    public var variableValue: Bool

    public init(variableName: String, variableValue: Bool) {
        self.variableName = variableName
        self.variableValue = variableValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case variableName
        case variableValue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(variableName, forKey: .variableName)
        try container.encode(variableValue, forKey: .variableValue)
    }
}

