//
// UniqueUserObjectAttribution.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UniqueUserObjectAttribution: Codable, JSONEncodable, Hashable {

    public var attribution: Attribution?
    public var searchads: AppleSearchAdsAttribution?

    public init(attribution: Attribution? = nil, searchads: AppleSearchAdsAttribution? = nil) {
        self.attribution = attribution
        self.searchads = searchads
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attribution
        case searchads
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attribution, forKey: .attribution)
        try container.encodeIfPresent(searchads, forKey: .searchads)
    }
}

